### ISSUE TITLE
decide on UI

### ISSUE THREAD

**Issue by HenniePenny** [HenniePenny/Study-Buddy#28]

**Comment by tlcoles** [comment]
Use templates and elements of https://adminlte.io/

**Comment by tlcoles** [comment]
Use color palette based on Study Buddy logo https://coolors.co/palette/6b6ca9-648ab4-59bcc8-dcebf9

**Comment by tlcoles** [comment]
@HenniePenny I will open this branch and install adminLTE to then test a csv upload page

**Comment by tlcoles** [comment]
git fetch origin
git checkout 28-decide-on-ui
